language: node_js
cache: yarn
node_js:
  - "11"

script:
  - yarn lint
  - yarn build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master